### PR TITLE
Fix saved

### PR DESCRIPTION
**Pull request by JJwilkin**

### CODE REVIEW

**Comment by JJwilkin** [comment]
What was changed:
- Saved behaviour should now work in all circumstances
- There are now 10 API keys that auto switch,
- Empty Page is now center with lists text align :left 
- Empty Page icons are higher rez and fill up entire section
- Updated saved Recipe empty page text to since the paragraph was causing alignment issues

**Comment by JJwilkin** [comment]
I also added a custom loading screen... i'm not sure how I feel about it,  but I think it looks cool

**Comment by rajwanialiya** [comment]
> "i'm not sure how I feel about it, but I think it looks cool"
I sat and stared at this for at least 45secs super confused

**Review by rajwanialiya — APPROVED** [review]
very nice jefferson!

**Pull request merged**
